import React from 'react'

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'

import { SnackbarProvider } from '@/app/providers/SnackBarProvider'

import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <AppRouterCacheProvider>
          <SnackbarProvider>{children}</SnackbarProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
